rvm: 2.5.1
osx_image: xcode9.3
language: objective-c
cache: 
    bundler: true 
    cocoapods: true
    directories:
        - /home/travis/.rvm/
bundler_args: --without=documentation
podfile: Podfile
script:
    - bundle exec fastlane test_in_travis
    - bundle exec pod lib lint




