rvm: 2.5.1
osx_image: xcode9.3
language: objective-c
cache: 
    bundler: true 
    cocoapods: true
    directories:
        - /home/travis/.rvm/
podfile: Podfile
install:
    - bundle install --without=documentation
    - bundle exec pod install
script:
    - bundle exec fastlane test_in_travis
    - bundle exec pod lib lint
after_success: 
    - bash <(curl -s https://codecov.io/bash) -f ./fastlane/test_output/code_coverage/cobertura.xml




